In [2]:

import torch


In [3]:
x_pt = torch.tensor(25) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25)

In [4]:

x_pt.shape

torch.Size([])

In [5]:
#vectors in pytorch

In [6]:
x_pt = torch.tensor([25, 2, 3])
x_pt

tensor([25,  2,  3])

In [7]:
#MATRICES IN PYTORCH

In [8]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [9]:
X_pt.shape

torch.Size([3, 2])

In [10]:
X_pt[1, :]

tensor([ 5, 26])

In [11]:
images_pt = torch.zeros([32, 28, 28, 3])

In [12]:
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [13]:
#BASIC TENSOR ARITHMETIC

In [14]:
X_pt*2+2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [15]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [16]:
A_pt = X_pt + 2
A_pt

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [17]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [18]:
A_pt * X_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [19]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [20]:
torch.sum(X_pt)

tensor(68)

In [21]:
torch.sum(X_pt, 0)

tensor([33, 35])

In [22]:
x_pt

tensor([25,  2,  3])

In [23]:
y_pt = torch.tensor([0, 1, 2])
y_pt

tensor([0, 1, 2])

In [24]:
#so we nned make integers float in pytorch so that can work 
torch.dot(torch.tensor([25, 2, 5.]), torch.tensor([0, 1, 2.]))

tensor(12.)

In [25]:
X_pt = torch.tensor([[1, 2], [3, 4.]])  # torch.norm() requies float type
X_pt

tensor([[1., 2.],
        [3., 4.]])

In [26]:
torch.norm(X_pt)

tensor(5.4772)

In [27]:
#matrix multiplication

In [28]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [31]:
b_pt = torch.tensor([[1],
                   [2]])
b_pt

tensor([[1],
        [2]])

In [32]:
torch.matmul(A_pt, b_pt)

tensor([[11],
        [17],
        [23]])