In [3]:
import tensorflow as tf

In [4]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [5]:
x_tf.shape

TensorShape([])

In [6]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [7]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [8]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [9]:
tf_sum.numpy()  # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa

np.int16(28)

In [10]:
type(tf_sum.numpy())

numpy.int16

In [11]:
tf_float = tf.Variable(25., dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

In [12]:
#vectors in tensorflow

In [13]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [14]:
#MATRICES IN TENSORFLOW

In [15]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [17]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [19]:
X_tf[1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>